---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mysql
