---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - git
    - mongodb-server
    - mongodb-dev
    - redis-server
    - nodejs
    - npm

- name: ensure that grunt is installed using npm
  npm:
    name: grunt-cli
    state: latest
    global: yes

- name: ensure that node links to nodejs
  file:
    path: /usr/local/bin/node
    src: /usr/bin/nodejs
    state: link

