---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mysql

- name: ensure that owncloud group exists
  group:
    name: owncloud
    state: present

- name: ensure that owncloud user exits
  user:
    name: owncloud
    group: owncloud
    home: /srv/owncloud
    createhome: no
    shell: /bin/bash
    comment: owncloudLab User
    state: present

- name: ensure /var/cache/ansible directory exists
  file:
    path: /var/cache/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download the owncloud install package
  get_url:
    url: http://download.owncloud.org/community/owncloud-6.0.3.tar.bz2
    dest: /var/cache/ansible/owncloud.tar.bz2

- name: unarchive owncloud to /srv/owncloud
  command: tar xvjf /var/cache/ansible/owncloud.tar.bz2
           chdir=/srv
           creates=/srv/owncloud

- name: ensure /srv/owncloud is owned by owncloud user
  file:
    path: /srv/owncloud
    owner: owncloud
    group: owncloud
    recurse: yes


- name: update fpm owncloud configuration from template
  template:
    src: etc/php5/fpm/pool.d/owncloud.conf
    dest: /etc/php5/fpm/pool.d/owncloud.conf 
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm

- name: update nginx owncloud configuration from template
  template:
    src: etc/nginx/sites-available/owncloud
    dest: /etc/nginx/sites-available/owncloud
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: enable owncloud nginx configuration
  file:
    src: ../sites-available/owncloud
    path: /etc/nginx/sites-enabled/owncloud
    state: link
  notify:
    - restart nginx
