---
- name: check sharelatex out of git repository
  git:
    repo: https://github.com/sharelatex/sharelatex.git
    dest: /srv/sharelatex
    update: yes

- name: install npm packages
  npm:
    path: /srv/sharelatex
    state: latest
    global: yes

- name: run grunt install
  shell: grunt install && touch .grunt_install
         executable=/bin/bash
         chdir=/srv/sharelatex
         creates=/srv/sharelatex/.grunt_install
